[project]
name = "scanguard"
version = "0.1.0"
description = "ScanGuard"
readme = "README.md"
authors = [
    { name = "Peeyush ", email= ""},
    { name = "Harshit Batra", email = "68419702+N1CK99925@users.noreply.github.com" }
]
requires-python = ">=3.12.10"
dependencies = [
    "jupyter==1.1.1",
    "matplotlib==3.11.2",
    "notebook==7.6.2",
    "numpy==2.5.3",
    "pandas==3.0.6",
    "scikit-learn==1.9.1",
    "seaborn==0.13.2",
]

[project.scripts]
scanguard = "scanguard:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
